Function NewSpeedTestJ4
    Motor On
    Power High
    Real overHead, SpeedVar, i
    Speed 100
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 03/02/2026 15:47:37
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    TmReset 0
    PTCLR
    Accel 100, 100
    Go JA(0.000, 0.000, 0.000, 350.000)
    Wait 1
    gSpeedVar = 0
   	
   	'Xqt showPosition
   	'Wait 5
    For i = 1 To 10
    	SpeedVar = -((i - 11) * 10)
    	gSpeedVar = SpeedVar
    	Print "Speed:", SpeedVar
	    TmReset 0
	    Speed SpeedVar
	    Go JA(0.000, 0.000, 0.000, 350.000)
   		Go JA(0.000, 0.000, 0.000, -350.000)
	    overHead = Tmr(0)
	    Wait 1
	    Go JA(0.000, 0.000, 0.000, 350.000)
	    Wait 1
		Next
	Fend
