Function Joint1to2
    Motor On
    Power High
    Real overHead
    Speed 10
    Accel 10, 10

    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 03/02/2026 15:47:37
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    Go JA(0.000, -90, 0.000, 0.000)
    TmReset 0
    PTCLR
    'Accel 18, 18
    Go JA(0.000, -90, 0.000, 0.000)
    Go JA(180.000, 90, 0.000, 0.000)
    overHead = Tmr(0)
    Print overHead
    Wait 1
    
    
    Go JA(0.000, -90, 0.000, 0.000)
    TmReset 0
    PTCLR
    Go JA(0.000, -90, 0.000, 0.000)
    Go JA(0, 90, 0.000, 0.000)
    overHead = Tmr(0)
    Print overHead
    Wait 1
Fend

