Function PowerVerify
    Motor On
    Power High
    Speed 50
    Accel 100, 100
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 17/02/2026 16:31:09
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, -90.000, 0.000, 0.000)
    Go JA(90.000, 0.000, 0.000, 0.000)
    Go JA(0.000, 0.000, 0.000, 0.000)
Fend

