Function SpeedCurve
    Real overHead, i, SpeedVar
    Motor On
    Power High
    Speed 100
    Accel 100, 100
	Go JA(0.000, 0.000, 0.000, 0.000)
	Wait 1
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 26/02/2026 12:09:41
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
	For i = 1 To 10
		SpeedVar = i * 10
		Speed SpeedVar
	    TmReset 0
		Go JA(0.000, 0.000, 0.000, 0.000)
		Go JA(180.000, -90.000, -170.000, -90.000)
		Wait 0.03
		Go JA(0.000, 0.000, 0.000, 0.000)
		overHead = Tmr(0)
		Print SpeedVar, overHead

		Wait 1
	Next
Fend

