Function AccelCurve
    Real overHead, i, AccelVar
    Motor On
    Power High
    Speed 50
	Accel 50, 50
	Go JA(0.000, 0.000, 0.000, 0.000)
	Wait 1
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 26/02/2026 12:09:41
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
	For i = 1 To 10
		AccelVar = i * 10
		Accel AccelVar, AccelVar
	    TmReset 0
		Go JA(0.000, 0.000, 0.000, 0.000)
		Go JA(180.000, -90.000, -170.000, -90.000)
		Wait 0.03
		Go JA(0.000, 0.000, 0.000, 0.000)
		overHead = Tmr(0)
		Print AccelVar, overHead

		Wait 1
	Next
Fend

