Function behrad
    Motor On
    Power High
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 19/03/2026 13:06:16
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(132.440, 0.000, -180.000, -10.840)
Fend

