Function NewAccelTestJ1
    Motor On
    Power High
    Real overHead, AccelVar, i
    Speed 100
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 03/02/2026 15:47:37
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    TmReset 0
    PTCLR
    Accel 100, 100
    Go JA(0.000, 0.000, 0.000, 0.000)
    Wait 1
    gAccelVar = 0
   	
   	Xqt showPositionAccel
   	Wait 10
    For i = 1 To 10
    	AccelVar = i * 10
    	gAccelVar = AccelVar
    	Print "Accel:", AccelVar
	    TmReset 0
	    Accel AccelVar, AccelVar
	    Go JA(0.000, 0.000, 0.000, 0.000)
	    Go JA(180.000, 0.000, 0.000, 0.0000)
	    overHead = Tmr(0)
	    Wait 1
	    Go JA(0.000, 0.000, 0.000, 0.000)
	    Wait 1
		Next
	Fend
	
Function showPositionAccel
    Real PreviousAccel, check

    TmReset 1
    OpenNet #201 As Server
    WaitNet #201
    Print #201, "READY"

    PreviousAccel = gAccelVar   ' initialise so first loop is clean

    Do
        check = gAccelVar - PreviousAccel
        If check <> 0 Then
            Print #201, "EVENT,ACCEL,", gAccelVar, ",", Tmr(1)
        EndIf

        P99 = RealPos
        Print #201, "DATA,", CX(P99), ",", CY(P99), ",", CZ(P99), ",", Tmr(1)
		PreviousAccel = gAccelVar
        Wait 0.01
    Loop
Fend


