Function AccelTestRoboDkJoint2
    Motor On
    Power High
    Real overHead
    Speed 100
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 03/02/2026 15:47:37
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    TmReset 0
    PTCLR
    'Accel 18, 18
    Go JA(0.000, 90.000, 0.000, 0.000)
    Wait 1
   
    
    TmReset 0
    Accel 10, 10
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.0000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 10,10"
    Print overHead
    
    Wait 1
    TmReset 0
    Accel 20, 20
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 20,20"
    Print overHead
    
    Wait 1
    TmReset 0
    Accel 30, 30
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 30,30"
    Print overHead
    
        Wait 1
    TmReset 0
    Accel 40, 40
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 40, 40"
    Print overHead
    
        Wait 1
    TmReset 0
    Accel 50, 50
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 50, 50"
    Print overHead
    
        Wait 1
    TmReset 0
    Accel 60, 60
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 60,60"
    Print overHead
    
        Wait 1
    TmReset 0
    Accel 70, 70
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 70,70"
    Print overHead
    
        Wait 1
    TmReset 0
    Accel 80, 80
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 80,80"
    Print overHead
    
        Wait 1
    TmReset 0
    Accel 90, 90
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 90,90"
    Print overHead
    

    Wait 1
    TmReset 0
    Accel 100, 100
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 100,100"
    Print overHead
    
    Wait 1
    TmReset 0
    Accel 110, 110
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 110,110"
    Print overHead
    
        Wait 1
    TmReset 0
    Accel 120, 120
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Accel 120,120"
    Print overHead
    
Fend

