Function SpeedTestRoboDkJoint2
    Motor On
    Power High
    Real overHead
    Speed 100
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 03/02/2026 15:47:37
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    TmReset 0
    PTCLR
    Accel 100, 100
    Go JA(0.000, 90.000, 0.000, 0.000)
    Wait 1
     
    TmReset 0
    Speed 100
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.0000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 10"
    Print overHead
    
    Wait 1
    TmReset 0
    Speed 90
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 20"
    Print overHead
    
    Wait 1
    TmReset 0
    Speed 80
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 30"
    Print overHead
    
        Wait 1
    TmReset 0
    Speed 70
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed  40"
    Print overHead
    
        Wait 1
    TmReset 0
    Speed 60
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed  50"
    Print overHead
    
        Wait 1
    TmReset 0
    Speed 50
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 60"
    Print overHead
    
        Wait 1
    TmReset 0
    Speed 40
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 70"
    Print overHead
    
        Wait 1
    TmReset 0
    Speed 30
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 80"
    Print overHead
    
        Wait 1
    TmReset 0
    Speed 20
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 90"
    Print overHead
    

    Wait 1
    TmReset 0
    Speed 10
    Go JA(0.000, 90.000, 0.000, 0.000)
    Go JA(0.000, -90.000, 0.000, 0.000)
    overHead = Tmr(0)
    Wait 1
    Go JA(0.000, 90.000, 0.000, 0.000)
    Print "Speed 100"
    Print overHead
    
  	Fend

