Function Joint2PeakTest
    Motor On
    Power High
    Real overHead, SpeedVar, i
    Speed 100
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 03/02/2026 15:47:37
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    TmReset 0
    PTCLR
    Speed 100
    Accel 100, 100
    Go JA(0.000, 90.000, 0.000, 0.000)
    Wait 1
    gSpeedVar = 0
   	
   	TmReset 0
   	'Xqt showPosition
   	'Wait 10
    For i = 1 To 3
	    Go JA(0.000, 90.000, 0.000, 0.000)
    	Go JA(0.000, -90.000, 0.000, 0.0000)
	    overHead = Tmr(0)
	    Wait 1
	    Go JA(0.000, 90.000, 0.000, 0.000)
	    Wait 1
		Next
		overHead = Tmr(0)
		Print overHead
		
	Fend
