Function Joint1PowerAwesome
    Motor On
    Power High
    Real overHead, totaltime
    ' Program generated by RoboDK v5.9.6 for Epson_G6_451s on 03/02/2026 15:47:37
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    Accel 50, 50
    TmReset 0
    Go JA(0.000, 0.000, 0.000, 0.000)
    Wait 1
   
    TmReset 1
    TmReset 0
    Speed 100
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
    overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1

    TmReset 0
    Speed 90
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
    overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1
    
    TmReset 0
    Speed 80
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
    overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1
    
    TmReset 0
    Speed 70
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
    overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1

    TmReset 0
    Speed 60
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
   	overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1

    TmReset 0
    Speed 50
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
   	overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1
    
    TmReset 0
    Speed 40
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
   	overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1
    
    TmReset 0
    Speed 30
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
    overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1

    TmReset 0
    Speed 20
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
    overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1

    TmReset 0
    Speed 10
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(180.000, 0.000, 0.000, 0.0000)
    Go JA(0.000, 0.000, 0.000, 0.000)
    overHead = Tmr(0)
    Print "Speed 100"
    Print overHead
    Wait 1
    totaltime = Tmr(1)
    Print ("Total Time")
    Print (totaltime)
Fend

