Function prog1
    Motor On
    Power High
    Speed 100
    ' Program generated by RoboDK v5.9.2 for My Mechanism on 31/10/2025 15:10:42
    ' Using nominal kinematics.
    ' Using reference: My Mechanism Base
    ' Exporting targets with respect to the robot base
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(60.000, 30.000, 0.000, 0.000)
    Go JA(0.000, 0.000, 0.000, 0.000)
Fend

