Function Robot_Test1
    Motor On
    Power High
    Speed 100
    Wait 4
    ' Program generated by RoboDK v5.9.2 for Epson_G6_451s on 04/11/2025 15:15:27
    ' Using nominal kinematics.
    ' Using reference: Epson_G6_451s Base
    ' Exporting targets with respect to the robot base
    Go JA(0.000, 0.000, 0.000, 0.000)
    Go JA(41.640, 45.120, -81.820, 0.000)
    Go JA(116.650, 45.120, -11.520, 0.000)
    Go JA(116.650, 45.120, -136.360, 0.000)
    Go JA(0.000, 0.000, 0.000, 0.000)
Fend




